openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /compute/virtualmachines:
    get:
      tags:
      - cloud-cost-controller
      operationId: listAllVirtualMachines
      parameters:
      - name: page
        in: query
        description: Zero-based page index (0..N)
        required: false
        schema:
          minimum: 0
          type: integer
          default: 0
      - name: size
        in: query
        description: The size of the page to be returned
        required: false
        schema:
          minimum: 1
          type: integer
          default: 20
      - name: sort
        in: query
        description: "Sorting criteria in the format: property(,asc|desc). Default\
          \ sort order is ascending. Multiple sort criteria are supported."
        required: false
        schema:
          type: array
          items:
            type: string
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PageVMCompute'
    post:
      tags:
      - cloud-cost-controller
      operationId: saveVMComputeDetails
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VMCompute'
        required: true
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VMCompute'
  /compute/virtualmachines/{id}:
    get:
      tags:
      - cloud-cost-controller
      operationId: getVMComputeDetailsById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/VMCompute'
components:
  schemas:
    VMCompute:
      type: object
      properties:
        name:
          type: string
        cloudVendor:
          type: string
        id:
          type: integer
          format: int64
        type:
          type: string
        vcpus:
          type: string
        memory:
          type: string
        operatingSystem:
          type: string
        ip6support:
          type: boolean
        networkBandwidth:
          type: string
        family:
          type: string
        instanceStorage:
          type: string
        createdDate:
          type: integer
          format: int64
        modifiedDate:
          type: integer
          format: int64
    PageVMCompute:
      type: object
      properties:
        totalPages:
          type: integer
          format: int32
        totalElements:
          type: integer
          format: int64
        numberOfElements:
          type: integer
          format: int32
        pageable:
          $ref: '#/components/schemas/PageableObject'
        size:
          type: integer
          format: int32
        content:
          type: array
          items:
            $ref: '#/components/schemas/VMCompute'
        sort:
          $ref: '#/components/schemas/Sort'
        first:
          type: boolean
        last:
          type: boolean
        number:
          type: integer
          format: int32
        empty:
          type: boolean
    PageableObject:
      type: object
      properties:
        paged:
          type: boolean
        unpaged:
          type: boolean
        pageNumber:
          type: integer
          format: int32
        pageSize:
          type: integer
          format: int32
        offset:
          type: integer
          format: int64
        sort:
          $ref: '#/components/schemas/Sort'
    Sort:
      type: object
      properties:
        sorted:
          type: boolean
        unsorted:
          type: boolean
        empty:
          type: boolean

